### PR TITLE
Update PaaS FAQ to be accurate

### PR DESCRIPTION
**Pull request by mgough-ukcloud**
Updating schedule section and removing old information.

### CODE REVIEW

**Comment by mgough-ukcloud** [comment]
@suehighmoor - don't suppose you can help me with the way the tables are presented? Ideally, if they could be displayed side-by-side it would be much better. However, i couldn't figure out a way to do it.

**Comment by suehighmoor** [comment]
@mgough-ukcloud - I put the tables next to each other by just inserting an empty column. Not sure how this works for you... If you're not happy with it, I could try and put an HTML table directly into the markdown and play around the with borders to make it look more like two separate tables.

**Comment by mgough-ukcloud** [comment]
> I put the tables next to each other by just inserting an empty column. 

I'm perfectly happy with that @suehighmoor - it achieves the look I was going for in the document, thank you!

@gsmith101 and @ARapisardaUKC - please may you review the changes to the document and, if you're happy, approve?

**Review by gsmith101 — APPROVED** [review]
Nice Matt this should really help customers understand the service that we offer

**Comment by ARapisardaUKC** [comment]
LGTM - I cant review files changed for some reason

**Comment by mgough-ukcloud** [comment]
Hi @suehighmoor - can we merge this one now? Adri and George have given approval (even if Adri's hasn't officially done).

**Pull request merged**
