### PR TITLE
added section for terraform authentication

### PR DESCRIPTION
**Pull request by brycenicholls**
As OSP 13 uses SSO, terraform fails authentication using the standard rcfile.
I have added a section to append the OS_TOKEN environment variable to the rdfile.

### CODE REVIEW

**Comment by brycenicholls** [comment]
@suehighmoor  Do I need to do anything else to get this merged? 
Thanks

**Comment by suehighmoor** [comment]
@brycenicholls, you just need to make sure that you've addressed @scassidy-ukcloud's comment, then we'll be good to go

**Comment by brycenicholls** [comment]
> it may be worth pointing out, if a token is created it will expire after a few hours and will need another one to be created after the expiration

@scassidy-ukcloud  I don't think it is relevant here because the terraform script will have completed it's work long before the token expires, but i can add a section if you feel it is needed.

**Comment by brycenicholls** [comment]
> @brycenicholls, you just need to make sure that you've addressed @scassidy-ukcloud's comment, then we'll be good to go

@suehighmoor  I have updated the documentation

**Comment by suehighmoor** [comment]
@scassidy-ukcloud, could you approve if you're happy with the update? Thanks!

**Comment by suehighmoor** [comment]
Approved via email

**Pull request merged**
