### PR TITLE
Updated API call to work with vcloud 9.1

### PR DESCRIPTION
**Pull request by DudeleeG2**

### CODE REVIEW

**Comment by suehighmoor** [comment]
@DudeleeG2, could  you add someone who could do a quick technical review?

**Comment by cblackuk** [comment]
For as long as this is the right API we actually need... LGTM :-)

**Comment by suehighmoor** [comment]
@DudeleeG2, are we good to go with this, or does @andywis need to review before merging?

**Comment by DudeleeG2** [comment]
We should be good to go on this as Chris is familiar enough with powershell and vcloud

**Pull request merged**
