### PR TITLE
Updated content for new process

### PR DESCRIPTION
**Pull request by suehighmoor**

### CODE REVIEW

**Comment by suehighmoor** [comment]
Do not merge until changes to process implemented

**Comment by gellner** [comment]
@gellner will check that these permissions are open to all

**Comment by koneill94** [comment]
@stevemul @suehighmoor Change is scheduled on 09/01 that will enable OpenShift permissions for all portal accounts. Users are now automatically added to the correct SSO groups. Pending re-review this should be good to merge after 09/01.

**Comment by suehighmoor** [comment]
PR superseded by PR #996

**Pull request closed without merging**
