### PR TITLE
Update Portal Permissions Overview

### PR DESCRIPTION
**Pull request by bensaunders**
* Support and OpenStack permissions have moved to other pages.
* OpenShift permissions were always on a different page.
* Monitoring permissions have been removed entirely, to correspond with the changes to the Security Operations Service page.

### CODE REVIEW

**Comment by bensaunders** [comment]
Mark and I noticed that the links to the OpenShift and OpenStack guides were broken.

**Comment by bensaunders** [comment]
> Mark and I noticed that the links to the OpenShift and OpenStack guides were broken.

This is fixed at 280d4823e.

**Review by myoung-ukcloud — APPROVED** [review]
LGTM

**Review by suehighmoor — APPROVED** [review]
LGTM

**Pull request merged**
