### PR TITLE
No longer needed. COR5 being sunset

### PR DESCRIPTION
**Pull request by brycenicholls**
COR5 is being decomissioned.
We are using Octavia in COR5-2
Octavia being deployed to FRN6 imminently

### CODE REVIEW

**Review by nebupm — APPROVED** [review]
looks ok

**Comment by suehighmoor** [comment]
Closes #1697

**Review by srelf-ukcloud — APPROVED** [review]
LGTM

**Review by suehighmoor — APPROVED** [review]
LGTM

**Pull request merged**
