### PR TITLE
2fa for sso

### PR DESCRIPTION
**Pull request by suehighmoor**
First draft of 2FA article for SSO. Please review and provide specific info for date.

### CODE REVIEW

**Comment by suehighmoor** [comment]
Updated per review comments. @cam-ukcloud let me know if you need me to make any more changes.

**Comment by lje0401** [comment]
@cam-ukcloud, there is no mention of removing your existing token from your phone. Are you happy that, that is only covered in the Portal and not in this guide?

**Comment by cam-ukcloud** [comment]
@lje0401 step 1 in this guide says says "Open the app that you use to generate the 2FA code and remove the existing UKCloud entry.", I think the fact you've said it's not covered means this is not clear enough?

**Comment by lje0401** [comment]
@cam-ukcloud, yeah missed that completely, would recommend that its a separate step. Personally I would also recommend that the user doesn't remove it until they have set the new code up successfully.

**Comment by cam-ukcloud** [comment]
Looking at the combination of the article steps and the steps in the screenshot I think it is clear enough.

**Comment by cam-ukcloud** [comment]
@suehighmoor Do you have any objections to changing the title of the article to "Resetting Two-Factor Authentication for Single Sign On"?

**Comment by suehighmoor** [comment]
No objections. I'll change the title

**Comment by cam-ukcloud** [comment]
Sounds good @suehighmoor.  Not plans to change the UI.

**Comment by suehighmoor** [comment]
Changed title and fixed broken image. @cam-ukcloud, @lje0401 happy to approve?

**Comment by suehighmoor** [comment]
Article is ready to go @cam-ukcloud let me know when you want it to go live on the KC.

**Comment by cam-ukcloud** [comment]
Thanks @suehighmoor . It can go live now, as I will then get Amanda to update the Service Status page which will reference this article.

**Pull request merged**
