### PR TITLE
Update to how to add OpenShift Users

### PR DESCRIPTION
**Pull request by gellner**
- Updated this page to include instructions about using the new "OpenShift Permissions" tab
- Added Note about the occasional need for UKCloud engineers to add themselves to Portal / OpenShift

### CODE REVIEW

**Comment by suehighmoor** [comment]
Can we close down PR561?

**Comment by gellner** [comment]
> 
> 
> Can we close down PR #561?

I guess we can. I think I've included all the same details in this PR plus some new images. :'-(

**Comment by gellner** [comment]
> Made some changes (including the title). @gellner you might want to quickly check that you're OK with these. Otherwise LGTM

That all looks good to me. Thanks @suehighmoor  !

**Comment by suehighmoor** [comment]
@stevemul, @benbacon, @j-butcher - this just needs a 2nd technical review so that it can be merged and published. Thanks!

**Comment by benbacon** [comment]
This looks good but do we want to:

- rename the file from oshift-how-create-users.md to something that more closely matches the title e.g. oshift-how-manage-access.md ?
- toc_title is stil "Create a new user" I assume this should be changed also?

What do you think @suehighmoor ?

**Comment by suehighmoor** [comment]
@benbacon - Good idea. I've changed the file name and fixed the toc_title metadata tag. Could you go ahead and approve if you're happy with the article now. Thanks!

**Pull request merged**
