### PR TITLE
Review azs-how-create-service-fabric-portal

### LINKED ISSUE #1638: 02/03/2021 - How to create a Service Fabric cluster using the UKCloud Azure Stack Hub portal - Review required
:page_facing_up: Title - How to create a Service Fabric cluster using the UKCloud Azure Stack Hub portal
:calendar: Expires - 02/03/2021
:family: Team - Azure Stack Review Team
:package: Product - UKCloud for Microsoft Azure
:link: [GitHub Link](https://github.com/UKCloud/documentation/tree/master/articles/azure/azs-how-create-service-fabric-portal.md)
:link: [Knowledge Centre Link](https://docs.ukcloud.com/articles/azure/azs-how-create-service-fabric-portal.html)

**Before making any changes, make sure you're familiar with our [guidelines](https://docs.ukcloud.com/articles/other/other-ref-knowledge-guidelines.html) for contributing to Knowledge Centre articles.**

### PR DESCRIPTION
**Pull request by wturner123**
Closes #1638

### CODE REVIEW

**Comment by suehighmoor** [comment]
> @suehighmoor do we need to make Service Fabric lowercase in most of this doc same as key vault as we are really referring to the object/cluster/instance of it not the actual product? I am not sure :-) help please

If it's an object name rather than a product name, we should use lowercase.

**Comment by cblackuk** [comment]
> > @suehighmoor do we need to make Service Fabric lowercase in most of this doc same as key vault as we are really referring to the object/cluster/instance of it not the actual product? I am not sure :-) help please
> 
> ~If it's an object name rather than a product name, we should use lowercase.~ Just checked the Microsoft docs and they use Init Caps for Service Fabric when refering to Service Fabric clusters, so we should probably stick with that. https://docs.microsoft.com/en-us/azure/service-fabric/overview-managed-cluster

But can that be trusted? :-)

**Review by suehighmoor — APPROVED** [review]
LGTM

**Review by cblackuk — APPROVED** [review]
LGTM

**Pull request merged**
