### PR TITLE
Oshift route dns update v4

### PR DESCRIPTION
**Pull request by koneill94**
Updated docs to describe difference in whitelisting needed for v4.4+ due to different routing path of the traffic. Also tided and removed an unnecessary 'important' block.

### CODE REVIEW

**Comment by suehighmoor** [comment]
@koneill94, can you just confirm that the information (IPs) shown in those screenshots are OK to share publicly or does anything need blurring?

**Review by suehighmoor — COMMENTED** [review]
@koneill94, could you just confirm that there's nothing sensitive in those two images (e.g., IDs or IPs) that should be blurred.

**Comment by koneill94** [comment]
> @koneill94, could you just confirm that there's nothing sensitive in those two images (e.g., IDs or IPs) that should be blurred.

Unsure how to blur - removed the IPs which might not be allowed in the mac preview app but I can't tell if its had an effect on the embedded image. Can you confirm?

**Comment by suehighmoor** [comment]
> > @koneill94, could you just confirm that there's nothing sensitive in those two images (e.g., IDs or IPs) that should be blurred.
> 
> Unsure how to blur - removed the IPs which might not be allowed in the mac preview app but I can't tell if its had an effect on the embedded image. Can you confirm?

Image updates have worked, thanks!

**Review by suehighmoor — APPROVED** [review]
LGTM

**Review by andrew-garner — APPROVED** [review]
LGTM

**Review by gellner — APPROVED** [review]
LGTM

**Comment by benbacon** [comment]
We have obfuscated the public IP address but not the hostname (which we could resolve to get the IP) - should this not be obfuscated also?

**Comment by stevemul** [comment]
Fixed the merge conflicts and removed the extra references to outdated terms in the outstanding PR. Should probably be re-reviewed though before merge.

**Review by stevemul — APPROVED** [review]
LGTM

**Review by gellner — APPROVED** [review]
LGTM

**Review by suehighmoor — APPROVED** [review]
LGTM

**Pull request merged**
