### PR TITLE
adding how to transfer volumes between projects

### PR DESCRIPTION
**Pull request by srelf-ukcloud**

### CODE REVIEW

**Comment by suehighmoor** [comment]
@srelf-ukcloud - I tidied the doc up a bit to make it a bit more structured. You might want to take a quick look through to make sure I didn't misinterpret anything...

**Comment by brycenicholls** [comment]
LGTM

**Review by brycenicholls — APPROVED** [review]

**Review by nebupm — APPROVED** [review]
Looks ok.

**Review by suehighmoor — APPROVED** [review]
LGTM

**Pull request merged**
