### PR TITLE
Identifying a VM in read only mode

### PR DESCRIPTION
**Pull request by suehighmoor**
New article to help customers identify if a VM is in read-only mode, and how to resolve

### CODE REVIEW

**Review by SteveHallUKCLoud — APPROVED** [review]
LGTM

**Review by mikepukcloud — COMMENTED** [review]
I added some event IDS to the windows section, but these are not included, any reason?

**Comment by suehighmoor** [comment]
> I added some event IDS to the windows section, but these are not included, any reason?

No idea how I managed to miss that. It's there now

**Review by mikepukcloud — APPROVED** [review]
Thanks for the changes, LGTM now

**Pull request merged**
