### PR TITLE
Update vmw-sd-vls.md

### PR DESCRIPTION
**Pull request by mikepukcloud**
As per Lara, change monthly reviews to quarterly

### CODE REVIEW

**Review by SteveHallUKCLoud — CHANGES_REQUESTED** [review]
Looks like a typo on the first edit

**Review by suehighmoor — COMMENTED** [review]
LGTM

**Review by suehighmoor — APPROVED** [review]
LGTM

**Comment by suehighmoor** [comment]
> Looks like a typo on the first edit

@SteveHallUKCLoud, I fixed the typo if you're happy to approve now?

**Review by SteveHallUKCLoud — APPROVED** [review]
LGTM

**Pull request merged**
