### PR TITLE
Cloud Director 10.1 - Update broken link

### PR DESCRIPTION
**Pull request by swthomas1**
Following conversation with Sue, used a more general link to replace broken link (has been raised with VMWare but no update).

### CODE REVIEW

**Review by suehighmoor — APPROVED** [review]
LGTM

**Review by meepsie206 — COMMENTED** [review]
Should we add the Cloud Director API endpoint change (UKClud dropped the `api.`) to this page?

**Comment by swthomas1** [comment]
Yes, we should John.

**Comment by meepsie206** [comment]
Yes it was.  It was when we upgraded from 9.7 to 10 and our first public version of 10 was 10.1.

**Review by meepsie206 — APPROVED** [review]
LGTM

**Pull request merged**
