### PR TITLE
updates mainly to move to newer language for control plane nodes

### PR DESCRIPTION
**Pull request by stevemul**
@suehighmoor - in line with the upstream community changes in OpenShift/Kubernetes I've changed a lot of the references in our service scopes etc to use the terminology control plane instead of master. This change was suggested by @m-digman and he's completed it in our pricing calculator this week. Can you have a look at what I've done so far and advise if there's a lot more to do here? I'm concious we shouldn't change instructions that relate to existing deployments that have nodes with the name of master as that'll make them less useful for users.

There are also diagrams that'll need to be updated, can you help me with how I get these updated too? 

An additional consideration is around the firewall filtering, I think general consensus now is to use the term allowlist/denylist instead of whitelist/blacklist. I've not done that yet here, but perhaps we should do it in the same PR?

This is clearly work in progress for now and not ready for merge, but we don't have a wip label I can use.

### CODE REVIEW

**Comment by stevemul** [comment]
This update work is completed and rolls in a couple of document reviews too. I haven't updated the images or their links as I haven't got copies, but as they're largely not visible to the readers this is probably less critical.

**Review by gellner — APPROVED** [review]
LGTM

The getting started changes may have some merge conflicts with https://github.com/UKCloud/documentation/pull/1258 though

**Review by andrew-garner — APPROVED** [review]
All the changes look good to me. I've not searched through the original documents for any missed references, I trust they have all been found.

**Review by suehighmoor — APPROVED** [review]
LGTM

**Pull request merged**
