### PR TITLE
Historic metrics update

### PR DESCRIPTION
**Pull request by swthomas1**
Historic metrics are now supported across all production regions following deployment of the required components within the last year.

### CODE REVIEW

**Review by suehighmoor — APPROVED** [review]
LGTM

**Comment by meepsie206** [comment]
We should update all our example Cloud Director URL's, dropping the `api.` which is no longer used since Cloud Director 10 rollout.  Although they are only examples and the customer should be looking up the URL from the portal, we could be confusing the customer by not using examples that are consistent with the production URL's.

**Review by meepsie206 — COMMENTED** [review]
Conversation on Cloud Director URL's added

**Review by meepsie206 — APPROVED** [review]
LGTM

**Pull request merged**
