### PR TITLE
Add v3 or v4 toc_sub1 categorisation for OCP version-specific docs

### PR DESCRIPTION
**Pull request by andrew-garner**
Add v3 or v4 to toc_sub1 to mark articles as specific to an OCP major version. 
Other minor markdown formatting changes.

### CODE REVIEW

**Comment by koneill94** [comment]
I've reviewed the articles here's my take on things that need changing (I wasn't sure what we were doing for generic articles at the start but I assume its a blank toc sub, I only realised this half way through so some of the ones I've listed as generic will already have that):

v3:

articles/openshift/oshift-how-obtain-usage-metrics.md
articles/openshift/oshift-how-view-router-logs.md
articles/openshift/oshift-ref-no-proxy.md 

generic:

articles/openshift/oshift-how-backup-directories-database.md
articles/openshift/oshift-how-build-app-private-repo.md
articles/openshift/oshift-how-expand-persistent-vols.md
articles/openshift/oshift-how-manage-user-access.md
articles/openshift/oshift-how-monitor-cluster.md
articles/openshift/oshift-how-restrict-access-to-openshift-routes-by-ip-address.md

possibly generic needs test:

articles/openshift/oshift-how-backup-migrate.md


needs minor edits to be generic:

articles/openshift/oshift-ref-cluster-monitoring.md
articles/openshift/oshift-ref-security-best-practices.md

should be under v3 and possibly another sub underneath same as the existing one:

articles/openshift/oshift-how-configure-portworx-volume-replication.md


For the ones that need testing or minor changes to be generic they could just be set to v3 for now and raise a jira ticket for them to be looked at and changed in a separate PR.

**Comment by suehighmoor** [comment]
Just trying to get my head around what we want to achieve here. Is the idea that we'll have some topics that will have both v3 and v4 versions or that the articles for v3 and v4 will be quite different? How do we want this to look in the TOC? At the moment, we'd have something like (which makes sense if the v3 and v4 articles will cover different topics):

How To
    Generic topics
    ...
    v3
        Obtain usage logs
        View router logs
        ...
    v4
        bunch of topics

But if we'll have v3 and v4 versions of the same article, it might make more sense to have something like:

How To
    Generic topics
    ...
    Obtain usage logs
        v3
        v4
    View router logs
        v3
        v4

**Comment by suehighmoor** [comment]
Just thinking about what we want this to look like in the TOC. What we've got at the moment will work if the topics covered in the v3 and v4 articles will be different - you'll get something like:

`How to`
`   Backup and restore...`
`   etc`
`   v3`
`      Obtain usage metrics`
`      View router logs`
`      etc`
`   v4`
`      bunch of articles`

But if you'll have v3 and v4 versions of the same article, it might make more sense to have something like:

`How to`
`   Backup and restore...`
`   etc`
`   Obtain usage metrics`
`      v3`
`      v4`
`   View router logs`
`      v3`
`      v4`

**Comment by andrew-garner** [comment]
If I was a customer I would prefer to browse everything available based on the version of OpenShift I am running. I find this more consistent with other online technical documentation, where I can select the version first and then browse everything available. I'm sure this could be argued either way though.

**Comment by suehighmoor** [comment]
Fair enough. Happy to push it out and see if it works. @andrew-garner - not sure what's happening about @koneill94's comments -will these be addressed before merging?

**Comment by suehighmoor** [comment]
@koneill94 - happy with the change?

**Review by suehighmoor — APPROVED** [review]
LGTM

**Review by koneill94 — APPROVED** [review]
LGTM

**Comment by suehighmoor** [comment]
@andrew-garner - do  you want any additional technical reviews on this or are you happy for me to merge and see what happens :)

**Comment by andrew-garner** [comment]
Hi @suehighmoor, we're happy to merge now. We're around to make changes if it doesn't work out as expected.

**Pull request merged**
