### PR TITLE
Update other-ref-external-security-review-testing.md

### PR DESCRIPTION
**Pull request by gsmith101**
Adding changes requested via email from Darren

### CODE REVIEW

**Comment by dcoombesukc** [comment]
Not sure what's up with this PR but there's no add review button - not sure if this is just me

**Review by dcoombesukc — APPROVED** [review]
LGTM - for some reason I had to comment on it first before it let me review!

**Comment by suehighmoor** [comment]
I think this may be covered by the PR created previously: #1664
@gsmith101, could you take a look and approve if it looks OK?

**Comment by suehighmoor** [comment]
covered by PR #1664

**Pull request closed without merging**
