### PR TITLE
Paul cantle shared updates

### PR DESCRIPTION
**Pull request by cantlep**
1) Internal document related hyperlinks remain pointing at their old counterparts in case you wanted to change the naming convention of my new documents
 
2) Once you're happy or have adjusted, i'll need to edit the 3 original documents to ask readers to reference these new ones

### CODE REVIEW

**Comment by cantlep** [comment]
Also, possible note required around the lack of consistent catalogue items in Assured for the moment (regarding the RHEL templates)

**Review by mikepukcloud — APPROVED** [review]
LGTM

**Comment by suehighmoor** [comment]
I've made some updates to clarify which articles are for RHUI 3 vs RHUI 2 and some other minor proofing edits.
@cantlep, might be worth you having a quick read through to confirm I've not introduced anything funky.

**Review by cantlep — COMMENTED** [review]
LGTM

**Comment by cantlep** [comment]
All looks good.

**Review by cantlep — COMMENTED** [review]
LGTM

**Review by suehighmoor — APPROVED** [review]
LGTM

**Pull request merged**
