### PR TITLE
Multiple Accounts Article

### PR DESCRIPTION
**Pull request by wakes63**
Final version of article

### CODE REVIEW

**Comment by danbaker7** [comment]
Just above the disadvantages section in the table, @wakes63 noticed two of the cells could be merged. 

It's probably not possible or even worth doing if it is. But I wanted to show her an example of a comment.

**Comment by suehighmoor** [comment]
Couldn't get the rowspan thing to work without messing up the rest of the table, so will leave as is for now

**Comment by suehighmoor** [comment]
Need to merge adding users article first

**Comment by cam-ukcloud** [comment]
Looks good, the only feedback I have re-reading it again is the cell in the table which is a disadvantage for a single account - "Provides less visibility of users and tickets that are all together in single lists." - why is there less visibility? Is the implication that it is harder to see the wood for the trees because people for different workloads are all the same list, and tickets for different projects are in the same view? If so I wonder if this could be rephrased somehow to make it clearer?

**Comment by suehighmoor** [comment]
Is this better:
Shows all tickets in a single list, making it more difficult to locate tickets for a particular project. Similarly with users for different workloads.

**Comment by wakes63** [comment]
Sounds good Sue

**Pull request merged**
