### PR TITLE
Update OpenShift Getting Started and Trial pages. cnap-1696

### PR DESCRIPTION
**Pull request by gellner**
A number of updates for OpenShift v4 - replaced docs.openshift.com links with their closest possible links in the v4.6 docs

I've archived the v3 Getting started guide into the Reference ... OpenShift v3 section in TOC

Updated a couple of images which are used in both version of the GS guide.

### CODE REVIEW

**Review by suehighmoor — APPROVED** [review]
LGTM

**Comment by suehighmoor** [comment]
Just one thing: in oshift-ref-trial.md, L53, should it be:
PVCs are used for pods...
or
PVCs are useful for pods...

**Review by andrew-garner — APPROVED** [review]
LGTM

**Review by koneill94 — APPROVED** [review]
LGTM

**Pull request merged**
