### PR TITLE
Fix azs sco doc

### PR DESCRIPTION
**Pull request by cblackuk**
Making it a bit more in line with where the product is heading.

### CODE REVIEW

**Review by SteveHallUKCLoud — APPROVED** [review]
LGTM - Thanks for completing Chris!

**Review by wturner123 — APPROVED** [review]
LGTM

**Comment by suehighmoor** [comment]
@SteveHallUKCLoud, @cblackuk - I reordered the content a little, similar to what we did previously for OpenShift to make the Service Scopes a bit more consistent and give a more logical structure. You might want to quickly scan through to confirm that it still makes sense.

**Review by SteveHallUKCLoud — APPROVED** [review]
LGTM

**Review by suehighmoor — APPROVED** [review]
LGTM

**Pull request merged**
