### PR TITLE
Update other-ref-best-practice-guide.md

### PR DESCRIPTION
**Pull request by DBroderick**
Adding a section for supported browsers

### CODE REVIEW

**Review by gsmith101 — APPROVED** [review]
Hi Darren,

Nice new section that is a very good idea based on recent events.

**Review by dcoombesukc — APPROVED** [review]
LGTM

**Comment by suehighmoor** [comment]
@gsmith101, I tweaked the wording a little bit. Do you want to just quickly check to make sure you're happy with the changes I made? Thanks!

**Comment by DBroderick** [comment]
Looks good to me @suehighmoor

**Review by suehighmoor — APPROVED** [review]
LGTM

**Pull request merged**
