### PR TITLE
Update cdsz-ref-application-process.md

### PR DESCRIPTION
**Pull request by bartchal**
only half complete but didnt finish. please approve changes but we will come back to this to finish. probably in the new year.

### CODE REVIEW

**Review by suehighmoor — APPROVED** [review]
LGTM

**Review by suehighmoor — APPROVED** [review]
LGTM
I won't close the underlying review issue until the article has been reviewed in its entirety

**Comment by suehighmoor** [comment]
Article has been reviewed offline by both the PM and the Service Director, therefore two Product Marketing reviews are sufficient here.

**Review by maynardjukc — APPROVED** [review]
LGTM

**Pull request merged**
