### PR TITLE
Ensuring responsibilities are clear

### PR DESCRIPTION
**Pull request by mgough-ukcloud**
Asked SDixon to confirm he is happy with the addition of two lines that increase the verbosity of the expected responsibilities of a man patching consumer. This isn't a change to the scope as much as it's just laying it out better.

### CODE REVIEW

**Comment by mgough-ukcloud** [comment]
SDixon gave approval via email

**Review by dbrennand — APPROVED** [review]
LGTM

**Review by gsmith101 — APPROVED** [review]
Nice addition to the existing guide.

**Review by suehighmoor — APPROVED** [review]
LGTM

**Pull request merged**
