### PR TITLE
azs-how-create-spn-powershell - Fix param name and change error format

### PR DESCRIPTION
**Pull request by wturner123**
As per title.

### CODE REVIEW

**Review by suehighmoor — APPROVED** [review]
LGTM

**Comment by suehighmoor** [comment]
@wturner123 - can we bump the last reviewed date, or does the article need a more thorough review for that?

**Comment by wturner123** [comment]
@suehighmoor - We'll merge this PR as is, but a further review will be done as we noticed some wider issues which needs addressing in this doc.
@cblackuk - To approve & merge.

**Review by cblackuk — APPROVED** [review]
LGTM

**Pull request merged**
