### PR TITLE
Portal API fix JSON syntax

### PR DESCRIPTION
**Pull request by ccouzens**
The syntax highlighting made it obvious that commas were missing

### CODE REVIEW

**Review by willllewellyn — APPROVED** [review]

**Review by m-digman — APPROVED** [review]

**Comment by myoung-ukcloud** [comment]
There are a couple of duplicate lines (336 & 337) in the example JSON:

                  "inBackup": true,
                  "lastBackupStatus": "Successful",

These are the same as lines 333 & 334. They should be removed.

**Comment by suehighmoor** [comment]
> There are a couple of duplicate lines (336 & 337) in the example JSON
@myoung-ukcloud, I've removed the duplicate lines, if you could just confirm and approve, thanks! Nice spot btw :)

**Review by myoung-ukcloud — APPROVED** [review]
Great, thank Sue. LGTM

**Review by suehighmoor — APPROVED** [review]
LGTM

**Pull request merged**
