### PR TITLE
Update oshift-how-create-users.md

### PR DESCRIPTION
**Pull request by gsmith101**
Matt Gough added some content to the Doc.

### CODE REVIEW

**Comment by gsmith101** [comment]
Yes good point Sue I have no Idea why I have done that

**Comment by gsmith101** [comment]
I think I have just mixed up the name of the branch by mistake. I believe that is this is committed it won't mess up the Docs page

**Comment by suehighmoor** [comment]
It looks like the file that has been edited is the OpenShift file though (articles/openshift/oshift-how-create-users.md). Might be best to just close this pull request.

**Comment by gsmith101** [comment]
Yes please cancel this and I will reupload a new copy at a later date.

**Pull request closed without merging**
