### PR TITLE
Update other-ref-dc-notice

### PR DESCRIPTION
**Pull request by suehighmoor**
Annual review of Data centre advance notice requirements.
Reviewed by SME; minor amends requested.

### CODE REVIEW

**Review by SteveHallUKCLoud — APPROVED** [review]
LGTM

**Review by ngatehouse1 — COMMENTED** [review]
I would like to query the change from 2 days to 24 hours. Talking to the frontline team this change would prove challenging in the real world. Interested who has requested the change so further discussion can take place. Thankyou

**Comment by suehighmoor** [comment]
Following feedback, I've added more detail to caveat the 24 hour notice and changed the cut off time for Monday requests

**Review by ngatehouse1 — APPROVED** [review]
I am happy with the additional changes

**Pull request merged**
